### ISSUE TITLE
Add header injection to SSRF scenario to support GCP use-case

### ISSUE THREAD

**Issue by raesene** [DataDog/vulnerable-java-application#1]
it's a little meta but for demonstration purposes it would be nice if we could either set arbitrary headers from the page (probably harder) or we hard-code the google metadata header to be sent `"Metadata-Flavor: Google"`

This would enable demonstrations that show the impact of SSRF in GCP cloud environments.

**Comment by christophetd** [comment]
As discussed, we can add a header injection in there
